### ISSUE TITLE
SyntaxError with Ubuntu 16.04's node-legacy install with default config

### ISSUE THREAD

**Issue by wilsonmfg** [tstringer/peachy-cli#1]
Steps to reproduce:

```
sudo apt install node-legacy npm
sudo npm install -g peachy-cli
peachy -h

```

output:

```
/usr/local/lib/node_modules/peachy-cli/src/peachy.js:251
  for (let i = 0; i < dataSourceTypes.length; i++) {
       ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/peachy-cli/peachy:2:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

```

**Comment by wilsonmfg** [comment]
"use strict"; doesn't seem to do it, so I'm guessing this requires a newer version of node?

**Comment by trstringer** [comment]
Thank you for bringing this to my attention!  It looks like it was introduced in [chrome v41 and sloppy mode in chrome v49](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#Browser_compatibility).  I'll do a little digging to get a min version for node.

What version of node are you using?

**Comment by wilsonmfg** [comment]
$ node --version
v4.2.6

**Comment by trstringer** [comment]
It looks like forcing strict mode does indeed fix this.  I have tested this on Ubuntu 16.04 and node v4.2.6.  The fix is included in [this commit](https://github.com/tstringer/peachy-cli/commit/82abbe16c2c9022553cd0648c1fccaa396e572bd).  I forced strict mode in the shebang line, and unfortunately you can only pass a single argument so I had to get around this by no longer relying on `env`.  I'm not happy about that, but at the moment this seems like the best solution.

Let me know if this is working for you now.  Thanks!

**Comment by trstringer** [comment]
I removed all occurrences of `let` in favor of being able to run this on a lower node version and keeping the shebang `env node` for portability.  Thanks for raising this issue and assisting with the resolution! 👍 😄
